stages:
  train2:
    cmd: python app/train_model.py
    deps:
    - app/train_model.py
    - data/row_dataset.xlsx
    outs:
    - models/model.joblib
  eval:
    cmd: python app/make_predictions.py
    deps:
    - app/make_predictions.py
    - data/row_dataset.xlsx
    metrics:
    - metrics/metrics.txt
